version: 2.1
#orbs:
#  ruby: circleci/ruby@0.1.2

jobs_orig:
  build:
    docker:
      - image: circleci/ruby:2.6.3-stretch-node
    executor: ruby/default
    steps:
      - checkout
      - run:
          name: Which bundler?
          command: bundle -v
      - ruby/bundle-install

commands:
  bundle_for_gem:
    description: Bundles and caches a gem.
    parameters:
      bundler_version:
        default: 2.0.1
        type: string
      cache_version:
        default: "1"
        type: string
      project:
        type: string
      ruby_version:
        type: string
    steps:
    - restore_cache:
        keys:
        - v<< parameters.cache_version >>-bundle-{{ checksum "Gemfile" }}--{{ checksum
          "<< parameters.project >>.gemspec" }}-<< parameters.ruby_version >>
        name: Restore bundle from cache
    - run:
        command: |
          echo 'export BUNDLER_VERSION=<< parameters.bundler_version >>' >> $BASH_ENV
          gem install bundler -v << parameters.bundler_version >>
        name: Update bundler
    - run:
        command: bundle check || bundle install
        name: Install dependencies
    - save_cache:
        key: v<< parameters.cache_version >>-bundle-{{ checksum "Gemfile" }}--{{ checksum
          "<< parameters.project >>.gemspec" }}-<< parameters.ruby_version >>
        name: Save bundle cache
        paths:
        - ~/project/vendor/bundle
  cached_checkout:
    description: Perform a cache-enabled git checkout.
    steps:
    - restore_cache:
        keys:
        - v1-source-{{ .Branch }}-{{ .Revision }}
        name: Restore code from cache
    - checkout
    - save_cache:
        key: v1-source-{{ .Branch }}-{{ .Revision }}
        name: Save code cache
        paths:
        - .git

jobs:
  bundle:
    parameters:
      ruby_version:
        type: string
        default: 2.4.10
      bundler_version:
        type: string
        default: 2.1.4
      rails_version:
        type: string
        default: '5.2.4.3'
    executor:
      # name: 'samvera/ruby'
      name: 'ruby'
      ruby_version: << parameters.ruby_version >>
    resource_class: medium+
    environment:
      RAILS_VERSION: << parameters.rails_version >>
      NOKOGIRI_USE_SYSTEM_LIBRARIES: true
    steps:
      - cached_checkout
      - bundle_for_gem:
          ruby_version: << parameters.ruby_version >>
          bundler_version: << parameters.bundler_version >>
          cache_version: '{{ checksum ".regen" }}'
          project: deepblue
      - persist_to_workspace:
          root: ~/
          paths:
          - project/*
          - project/**/*

  build:
    parameters:
      ruby_version:
        type: string
        default: '2.4.10'
      bundler_version:
        type: string
        default: '2.1.4'
      rails_version:
        type: string
        default: '5.2.4.3'
    executor:
      # name: 'samvera/ruby'
      name: 'ruby'
      ruby_version: << parameters.ruby_version >>
    resource_class: medium+
    environment:
      RAILS_VERSION: << parameters.rails_version >>
      NOKOGIRI_USE_SYSTEM_LIBRARIES: true
    steps:
      - attach_workspace:
          at: ~/
      - deepblue/bundle_for_gem:
          ruby_version: << parameters.ruby_version >>
          bundler_version: << parameters.bundler_version >>
          cache_version: '{{ checksum ".regen" }}'
          project: deepblue
      - persist_to_workspace:
          root: ~/
          paths:
          - project/*
          - project/**/*

executors:
  ruby:
    description: Box just Ruby
    docker:
    - image: circleci/<< parameters.ruby_type >>:<< parameters.ruby_version >>-node-browsers-legacy
    environment:
      BUNDLE_JOBS: 4
      BUNDLE_PATH: vendor/bundle
      BUNDLE_RETRY: 3
      RACK_ENV: test
      RAILS_ENV: test
      SPEC_OPTS: --profile 10 --format RspecJunitFormatter --out /tmp/test-results/rspec.xml
        --format progress
    parameters:
      ruby_type:
        default: ruby
        type: string
      ruby_version:
        default: '2.4.10'
        type: string

workflows:
  version: 2
  ruby2-4rails5-2:
    jobs:
      - bundle:
          ruby_version: '2.4.10'
          rails_version: '5.2.4.3'
      - lint:
          ruby_version: '2.4.10'
          requires:
            - bundle
      - build:
          ruby_version: '2.4.10'
          rails_version: '5.2.4.3'
          requires:
            - bundle
      - test:
          name: "rails5-2"
          ruby_version: '2.4.10'
          requires:
            - build
            - lint
