version: 2.1
#orbs:
#  ruby: circleci/ruby@0.1.2

jobs_orig:
  build:
    docker:
      - image: circleci/ruby:2.6.3-stretch-node
    executor: ruby/default
    steps:
      - checkout
      - run:
          name: Which bundler?
          command: bundle -v
      - ruby/bundle-install

jobs:
  bundle:
    parameters:
      ruby_version:
        type: string
        default: 2.4.10
      bundler_version:
        type: string
        default: 2.1.4
      rails_version:
        type: string
        default: '5.2.4.3'
    executor:
      # name: 'samvera/ruby'
      name: 'ruby/default'
      ruby_version: << parameters.ruby_version >>
    resource_class: medium+
    environment:
      RAILS_VERSION: << parameters.rails_version >>
      NOKOGIRI_USE_SYSTEM_LIBRARIES: true
    steps:
      - deepblue/cached_checkout
      - deepblue/bundle_for_gem:
          ruby_version: << parameters.ruby_version >>
          bundler_version: << parameters.bundler_version >>
          cache_version: '{{ checksum ".regen" }}'
          project: deepblue
      - persist_to_workspace:
          root: ~/
          paths:
          - project/*
          - project/**/*
